#!/usr/bin/env python3
import argparse
import sys
import os
import datetime
import json
import tempfile

def convert_mmcif_to_pdb(mmcif_str, query_name, iptm=None):
    """
    Parses the mmCIF output string generated by ESMFold2 and formats it 
    into a standard 80-column PDB file with REMARK headers.
    """
    lines = mmcif_str.split('\n')
    pdb_lines = []
    
    current_date = datetime.date.today().strftime("%Y-%m-%d")
    pdb_lines.append(f"REMARK    QUERY NAME: {query_name}")
    pdb_lines.append(f"REMARK    STRUCTURE PREDICTED USING ESMFOLD2, {current_date}")
    
    if iptm is not None:
        pdb_lines.append(f"REMARK    IPTM: {iptm:.5f}")
    
    atom_serial = 1
    chain_map = {}
    chain_letters = "HLABCDEFGIJKMNOPQRSTUVWXYZ"
    
    for line in lines:
        line = line.strip()
        if line.startswith("ATOM") or line.startswith("HETATM"):
            parts = line.split()
            if len(parts) < 18:
                continue
                
            record = parts[0]
            element = parts[1]
            atom_name = parts[2]
            res_name = parts[4]
            chain_id_full = parts[5]
            res_seq = int(parts[7])
            b_factor = float(parts[13]) 
            occupancy = float(parts[14])
            x = float(parts[15])
            y = float(parts[16])
            z = float(parts[17])
            
            if chain_id_full not in chain_map:
                if chain_id_full.endswith("_H") and "H" not in chain_map.values():
                    chain_map[chain_id_full] = "H"
                elif chain_id_full.endswith("_L") and "L" not in chain_map.values():
                    chain_map[chain_id_full] = "L"
                elif chain_id_full == "H" and "H" not in chain_map.values():
                    chain_map[chain_id_full] = "H"
                elif chain_id_full == "L" and "L" not in chain_map.values():
                    chain_map[chain_id_full] = "L"
                else:
                    for letter in chain_letters:
                        if letter not in chain_map.values():
                            chain_map[chain_id_full] = letter
                            break
                    else:
                        chain_map[chain_id_full] = "A" 
            
            chain_id = chain_map[chain_id_full]
            
            if len(atom_name) < 4:
                name_fmt = f" {atom_name:<3}"
            else:
                name_fmt = f"{atom_name[:4]:<4}"
                
            pdb_line = f"{record:<6}{atom_serial:>5} {name_fmt} {res_name:>3} {chain_id:1}{res_seq:>4}    {x:>8.3f}{y:>8.3f}{z:>8.3f}{occupancy:>6.2f}{b_factor:>6.2f}          {element:>2}"
            pdb_lines.append(pdb_line)
            atom_serial += 1
            
    pdb_lines.append("END")
    return "\n".join(pdb_lines)


def main():
    parser = argparse.ArgumentParser(description="Run ESMFold2 and output a structure and CSV metrics.")
    parser.add_argument("-i", "--inputfile", default=None, 
                        help="Input FASTA file containing one or more protein sequences")
    parser.add_argument("--json", default=None, 
                        help="JSON payload with heavy, light, and antigen sequences to evaluate directly")
    parser.add_argument("--tag", default="esf2", 
                        help="Tag for output files (default: esf2)")
    parser.add_argument("--outdir", default=None, 
                        help="Output directory (default: same directory as the input file)")
    parser.add_argument("--verbose", action="store_true", 
                        help="Print detailed processing information to STDERR")
    parser.add_argument("--refresh", action="store_true", 
                        help="Force recalculation even if the output file already exists")
    parser.add_argument("--budget", type=float, default=None,
                        help="Compute budget in hours (heuristically scales diffusion samples)")
    parser.add_argument("--activation-checkpointing", action="store_true",
                        help="Enable activation checkpointing on the model transformer blocks to reduce peak VRAM usage")
    parser.add_argument("--msa_max_depth", type=int, default=1024,
                        help="Maximum number of MSA sequences to randomly subsample each loop to prevent memory explosion (default: 1024)")

    args = parser.parse_args()

    def vprint(*pargs, **kwargs):
        if args.verbose:
            print(*pargs, file=sys.stderr, **kwargs)

    def eprint(*pargs, **kwargs):
        print(*pargs, file=sys.stderr, **kwargs)

    if not args.inputfile and not args.json:
        eprint("Error: Must provide either -i/--inputfile or --json.")
        sys.exit(1)

    is_json_mode = False
    temp_fasta_path = None
    basename = "complex"

    # 1. Resolve Paths & Input Mode
    if args.json:
        is_json_mode = True
        try:
            payload = json.loads(args.json)
        except json.JSONDecodeError as e:
            eprint(f"Error parsing JSON payload: {e}")
            sys.exit(1)
        
        heavy = payload.get("heavy", "")
        light = payload.get("light", "")
        antigen = payload.get("antigen", "")
        basename = payload.get("name", "json_query")
        
        linker = "GGGSGGGSGGGSGGGS"
        mab_seq = heavy + linker + light
        
        # Create temporary FASTA
        fd, temp_fasta_path = tempfile.mkstemp(suffix=".fasta", text=True)
        with os.fdopen(fd, 'w') as f:
            f.write(f">mAb\n{mab_seq}\n")
            f.write(f">antigen\n{antigen}\n")
        
        in_path = temp_fasta_path
    else:
        in_path = os.path.abspath(args.inputfile)
        basename = os.path.splitext(os.path.basename(in_path))[0]
        
        if args.outdir is not None:
            out_dir = os.path.abspath(args.outdir)
            os.makedirs(out_dir, exist_ok=True)
        else:
            out_dir = os.path.dirname(in_path)

        out_pdb = os.path.join(out_dir, f"{basename}.{args.tag}.pdb")
        out_csv = os.path.join(out_dir, f"{basename}.{args.tag}.csv")

        # 2. Check Refresh using the CSV as the primary target (File Mode Only)
        if not args.refresh:
            if os.path.exists(out_csv) and os.path.getsize(out_csv) > 0:
                vprint(f"Output file {out_csv} already exists. Skipping computation.")
                print(out_csv)
                sys.exit(0)

    # 3. Parse FASTA
    if not os.path.exists(in_path):
        eprint(f"Error: Input file '{in_path}' does not exist.")
        sys.exit(1)

    sequences = []
    with open(in_path, "r") as f:
        seq_id = ""
        seq_data = []
        for line in f:
            line = line.strip()
            if line.startswith(">"):
                if seq_id:
                    sequences.append((seq_id, "".join(seq_data)))
                seq_id = line[1:].split()[0]
                seq_data = []
            elif line:
                seq_data.append(line)
        if seq_id:
            sequences.append((seq_id, "".join(seq_data)))

    if not sequences:
        eprint("Error: No sequences found in the input FASTA.")
        sys.exit(1)

    # 4. Process Budget Flag
    num_diff_samples = 1
    if args.budget:
        # Heuristic mapping: assume ~1 minute per structure fold. 
        # H hours * 60 = X diffusion samples.
        num_diff_samples = max(1, int(args.budget * 60))
        vprint(f"Budget of {args.budget} hours provided. Scaling to {num_diff_samples} diffusion sample(s).")

    # 5. Load Model
    vprint("Loading ESM modules and biohub/ESMFold2 on GPU...")
    try:
        from esm.models.esmfold2 import ProteinInput, StructurePredictionInput, ESMFold2InputBuilder
        from transformers.models.esmfold2.modeling_esmfold2 import ESMFold2Model
        from torch.distributed.algorithms._checkpoint.checkpoint_wrapper import (
            CheckpointImpl,
            apply_activation_checkpointing,
            checkpoint_wrapper,
        )
        from transformers.models.esmc.modeling_esmc import UnifiedTransformerBlock as TransformerBlock
    except ImportError as e:
        eprint(f"Error importing ESM modules: {e}")
        if is_json_mode and temp_fasta_path and os.path.exists(temp_fasta_path):
            os.remove(temp_fasta_path)
        sys.exit(1)

    try:
        model = ESMFold2Model.from_pretrained("biohub/ESMFold2").cuda().eval()

        # Apply activation checkpointing to the language model blocks if explicitly requested
        if args.activation_checkpointing:
            vprint("Applying activation checkpointing to TransformerBlock layers to optimize memory...")
            apply_activation_checkpointing(
                model,
                checkpoint_wrapper_fn=lambda m: checkpoint_wrapper(m, checkpoint_impl=CheckpointImpl.NO_REENTRANT),
                check_fn=lambda module: isinstance(module, TransformerBlock),
            )

        # 6. Predict (Modified for Sequential Sampling to save VRAM)
        vprint(f"Folding {len(sequences)} sequence(s)...")
        protein_inputs = [ProteinInput(id=sid, sequence=seq) for sid, seq in sequences]
        spi = StructurePredictionInput(sequences=protein_inputs)

        results = []
        for i in range(num_diff_samples):
            vprint(f"Generating diffusion sample {i+1}/{num_diff_samples}...")
            # Pass num_diffusion_samples=1 but vary the seed per iteration
            sample_result = ESMFold2InputBuilder().fold(
                model, 
                spi, 
                num_loops=20, 
                num_sampling_steps=100, 
                num_diffusion_samples=1, 
                seed=i,
                msa_max_depth=args.msa_max_depth
            )
            results.append(sample_result)

        # Select the best model by pTM out of the sequentially collected list
        vprint(f"Selecting the best model out of {len(results)} sequential samples by pTM...")
        result = max(results, key=lambda r: float(r.ptm) if r.ptm is not None else -1.0)

        # 7. Extract Metrics
        plddt = float(result.plddt.mean()) if result.plddt is not None else 0.0
        ptm = float(result.ptm) if result.ptm is not None else 0.0
        iptm = float(result.iptm) if result.iptm is not None else 0.0
        
        vprint(f"Final Best Metrics -> pLDDT: {plddt:.3f}, pTM: {ptm:.3f}, ipTM: {iptm:.3f}")

        # 8. Write Outputs
        raw_mmcif_str = result.complex.to_mmcif()
        standard_pdb_str = convert_mmcif_to_pdb(raw_mmcif_str, query_name=basename, iptm=iptm)
        
        if is_json_mode:
            # Output strictly to STDOUT and skip file writing
            print(standard_pdb_str)
        else:
            with open(out_pdb, "w") as f:
                f.write(standard_pdb_str)

            # Write clean CSV
            with open(out_csv, "w") as f:
                f.write("query_name,pLDDT,pTM,ipTM\n")
                f.write(f"{basename},{plddt:.3f},{ptm:.3f},{iptm:.3f}\n")

            # 9. Output strictly to STDOUT
            print(out_csv)

    except Exception as e:
        eprint(f"Error during processing or writing: {e}")
        sys.exit(1)
    finally:
        # Clean up temporary files 
        if is_json_mode and temp_fasta_path and os.path.exists(temp_fasta_path):
            os.remove(temp_fasta_path)

if __name__ == "__main__":
    main()
